### PR TITLE
ci: mark release workflow as `workflow_dispatch`

### PR DESCRIPTION
**Pull request by anakryiko**
According to Github Actions, this should allow to trigger the workflow manually. Let's see.

Cc: Quentin Monnet <quentin@isovalent.com>

### CODE REVIEW

**Comment by anakryiko** [comment]
@qmonnet it seems like something about building bpftool from submodule is broken, it expects LLVM-14 which is not present? Any idea what's going on? Is the fix needed on bpftool side or retsnoop side? See https://github.com/anakryiko/retsnoop/actions/runs/6368016638/job/17287065875

**Comment by qmonnet** [comment]
Hi Andrii, I don't know where the issue comes from.

It looks like this is coming from bpftool side, given that the feature probe for LLVM passes but the build fails to find `libLLVM-14.so`:

```
Makefile.feature:158: Probing: feature-llvm
Makefile.feature:159: printf '%b\n' '#include <llvm-c/Core.h>\n' '#include <llvm-c/TargetMachine.h>\n' 'int main(void) {' '	char *triple = LLVMNormalizeTargetTriple("");' '	LLVMDisposeMessage(triple);' '	return 0;' '}' | cc  -I/usr/lib/llvm-14/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS  -L/usr/lib/llvm-14/lib  -Wall -Werror -x c - -lLLVM-14 -o /dev/null >/dev/null && (echo 1 && >&2 echo result: 1) || (echo 0 && >&2 echo result: 0)
result: 1
...                        libbfd: [ OFF ]
...               clang-bpf-co-re: [ on  ]
...                          llvm: [ on  ]
...                        libcap: [ OFF ]

[...]

gcc  [...] -lLLVM-14 [...] -o /home/runner/work/retsnoop/retsnoop/retsnoop/src/.output/bpftool/bootstrap/bpftool
/usr/bin/ld: cannot find -lLLVM-14: No such file or directory
```

I can't reproduce locally, I've got consistent results between the probe and the build on my setup (the probe does fail if `libLLVM-14.so` is missing). I'll try to reproduce on a GH runner to investigate.

Do you have any idea when the workflow broke? I note that you updated bpftool yesterday, but I [can't find changes for bpftool's build system on this diff](https://github.com/libbpf/bpftool/compare/eb56fba..e17d6cf). There were [some changes that you pulled in June](https://github.com/libbpf/bpftool/compare/8e721a4..eb56fba#diff-89b645ea7f08ab7abb168bfe3ef2346b3edd6a5faad3f3a12631bbd2524b4b10), do you know if bpftool built successfully after that?

**Comment by anakryiko** [comment]
hey @qmonnet, thanks for taking a look! I don't know when it broke, as this was the first time I used new action to create a release. I updated bpftool after I ran into problems in hope that latest version of bpftool might have a fix.

This fix for retsnoop's Makefile looks good, you can probably put those CFLAGS and EXTRA_CFLAGS after $(MAKE), though? Please do open a PR!

**Comment by qmonnet** [comment]
> you can probably put those CFLAGS and EXTRA_CFLAGS after $(MAKE), though?

Nope, secret Makefile feature - it's not the same. Passing before passes through the environment and does not override the Makefile contents; passing after passes via the command line and overwrites the contents, making the assignments inside of the Makefile useless ([more details](https://stackoverflow.com/a/48888825/3716552)), and the build fail.

> Please do open a PR!

OK will do :)

**Comment by anakryiko** [comment]
Yeah, I knew about the difference for before or after make "envvars", but I just didn't think it matters so much here. Good to know, put that bit into the PR as well, for posterity. Thanks!

**Comment by qmonnet** [comment]
Sure, I had documented it in the commit log already. The PR is at #52

**Pull request merged**
